[phases.setup]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxrender1", "libxext6"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python main.py"
